# Generated by Django 4.2.11 on 2024-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_benefits', models.TextField()),
                ('address', models.CharField(max_length=60)),
                ('job_details', models.TextField()),
                ('job_requirements', models.TextField()),
                ('interview_deadline', models.DateField(blank=True, null=True)),
                ('hired', models.BooleanField()),
                ('notes', models.TextField(null=True)),
                ('available_times', models.ManyToManyField(related_name='jobs', to='jobs.availabletime')),
            ],
        ),
    ]
